# -*- coding: utf-8 -*-
"""hyperparametres.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lc4vjJbW7SNAk0CP4gUa6pZmgrOLm55f

Configuration et Imports
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import numpy as np
import os

print(f" PyTorch: {torch.__version__}")
print(f" CUDA disponible: {torch.cuda.is_available()}")
print(f" Device: {'cuda' if torch.cuda.is_available() else 'cpu'}")

""" Chargement des Données MNIST"""

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

print("Telechargement de MNIST...")
train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=256, shuffle=False)

print(f" Train: {len(train_dataset)} images")
print(f" Test: {len(test_dataset)} images")

"""Definition du Modele"""

class ReseauFC(nn.Module):
    ACTIVATIONS = {
        'relu': nn.ReLU(),
        'tanh': nn.Tanh(),
        'sigmoid': nn.Sigmoid(),
    }

    def __init__(self, hidden_sizes=[256, 128], dropout_rate=0.3, activation='relu'):
        super().__init__()
        act_fn = self.ACTIVATIONS.get(activation, nn.ReLU())
        layers = []
        in_dim = 784

        for h in hidden_sizes:
            layers.extend([
                nn.Linear(in_dim, h),
                act_fn,
                nn.Dropout(p=dropout_rate) if dropout_rate > 0 else nn.Identity(),
            ])
            in_dim = h

        layers.append(nn.Linear(in_dim, 10))
        self.network = nn.Sequential(*layers)

    def forward(self, x):
        return self.network(x.view(x.size(0), -1))

model_test = ReseauFC()
print(f" Modele cree avec {sum(p.numel() for p in model_test.parameters()):,} parametres")

"""Fonction d'Entrainement"""

def entrainer(model, optimizer, nb_epochs=5, l1_lambda=0.0, l2_lambda=0.0, verbose=True):
    criterion = nn.CrossEntropyLoss()
    device = next(model.parameters()).device

    train_losses, val_losses, val_accs = [], [], []
    for epoch in range(1, nb_epochs + 1):
        model.train()
        running_loss = 0.0
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)

            optimizer.zero_grad()
            logits = model(X_batch)
            loss = criterion(logits, y_batch)
            if l1_lambda > 0:
                l1_norm = sum(p.abs().sum() for p in model.parameters())
                loss = loss + l1_lambda * l1_norm

            loss.backward()
            optimizer.step()
            running_loss += loss.item() * X_batch.size(0)
        train_loss = running_loss / len(train_loader.dataset)
        model.eval()
        val_loss_total, correct = 0.0, 0
        with torch.no_grad():
            for X_batch, y_batch in test_loader:
                X_batch, y_batch = X_batch.to(device), y_batch.to(device)
                logits = model(X_batch)
                val_loss_total += criterion(logits, y_batch).item() * X_batch.size(0)
                correct += (logits.argmax(1) == y_batch).sum().item()

        val_loss = val_loss_total / len(test_loader.dataset)
        val_acc = correct / len(test_loader.dataset)

        train_losses.append(train_loss)
        val_losses.append(val_loss)
        val_accs.append(val_acc)

        if verbose:
            print(f"  Epoque {epoch:02d}/{nb_epochs} | "
                  f"Loss train={train_loss:.4f} | "
                  f"Loss val={val_loss:.4f} | "
                  f"Acc val={val_acc*100:.2f}%")

    return train_losses, val_losses, val_accs

""" Experience A - Learning Rate"""

def experience_lr():
    print("EXPERIENCE A : Impact du Learning Rate (Adam)")
    learning_rates = [1e-4, 1e-3, 1e-2, 1e-1]
    resultats = {}

    for lr in learning_rates:
        print(f"\n lr = {lr}")
        model = ReseauFC(hidden_sizes=[256, 128], dropout_rate=0.3)
        optimizer = optim.Adam(model.parameters(), lr=lr)
        tl, vl, va = entrainer(model, optimizer, nb_epochs=5, verbose=False)
        resultats[lr] = {'train': tl, 'val': vl, 'acc': va}
        print(f"Meilleure acc val = {max(va)*100:.2f}%")
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Impact du Learning Rate (optimiseur Adam)", fontsize=14)
    for lr, res in resultats.items():
        axes[0].plot(res['train'], label=f"lr={lr}")
        axes[1].plot([a*100 for a in res['acc']], label=f"lr={lr}")

    axes[0].set_title("Perte (train)")
    axes[0].set_xlabel("Epoque")
    axes[0].set_ylabel("Cross-Entropy Loss")
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)
    axes[1].set_title("Precision (validation)")
    axes[1].set_xlabel("Epoque")
    axes[1].set_ylabel("Accuracy (%)")
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("resultats_learning_rate.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("\n Graphe sauvegarde : resultats_learning_rate.png")

    return resultats
resultats_lr = experience_lr()

"""Experience B - Optimiseurs"""

def experience_optimiseurs():
    print("\n" + "="*60)
    print("EXPERIENCE B : Comparaison SGD vs Adam vs RMSprop")
    print("="*60)

    configs = {
        'SGD (lr=0.01)': optim.SGD,
        'SGD + momentum': optim.SGD,
        'Adam (lr=1e-3)': optim.Adam,
        'RMSprop (lr=1e-3)': optim.RMSprop,
    }

    kwargs_map = {
        'SGD (lr=0.01)': dict(lr=1e-2),
        'SGD + momentum': dict(lr=1e-2, momentum=0.9),
        'Adam (lr=1e-3)': dict(lr=1e-3),
        'RMSprop (lr=1e-3)': dict(lr=1e-3),
    }

    resultats = {}
    for nom, cls in configs.items():
        print(f"\n  -> {nom}")
        model = ReseauFC(hidden_sizes=[256, 128], dropout_rate=0.3)
        opt = cls(model.parameters(), **kwargs_map[nom])
        tl, vl, va = entrainer(model, opt, nb_epochs=7, verbose=False)
        resultats[nom] = va
        print(f"Meilleure acc val = {max(va)*100:.2f}%")
    fig, ax = plt.subplots(figsize=(10, 5))
    fig.suptitle("Comparaison des methodes d'optimisation", fontsize=14)
    for nom, va in resultats.items():
        ax.plot([a*100 for a in va], marker='o', label=nom)

    ax.set_xlabel("Epoque")
    ax.set_ylabel("Accuracy (%) - validation")
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("resultats_optimiseurs.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("\n Graphe sauvegarde : resultats_optimiseurs.png")

    return resultats
resultats_opt = experience_optimiseurs()

"""Experience C - Regularisation"""

def experience_regularisation():
    print("\n" + "="*60)
    print("EXPERIENCE C : Regularisation L1 vs L2 (weight_decay)")
    print("="*60)
    configs = [
        ("Sans regularisation", 0.0, 0.0),
        ("L2 lambda=1e-4", 0.0, 1e-4),
        ("L2 lambda=1e-3", 0.0, 1e-3),
        ("L1 lambda=1e-5", 1e-5, 0.0),
        ("L1 lambda=1e-4", 1e-4, 0.0),
    ]

    resultats = {}
    for nom, l1, l2 in configs:
        print(f"\n  -> {nom}")
        model = ReseauFC(hidden_sizes=[256, 128], dropout_rate=0.0)
        opt = optim.Adam(model.parameters(), lr=1e-3, weight_decay=l2)
        tl, vl, va = entrainer(model, opt, nb_epochs=7, l1_lambda=l1, verbose=False)
        resultats[nom] = {'train': tl, 'val': vl, 'acc': va}
        print(f"Meilleure acc val = {max(va)*100:.2f}%")

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Impact de la regularisation L1 et L2", fontsize=14)

    for nom, res in resultats.items():
        axes[0].plot(res['train'], label=nom)
        axes[1].plot([a*100 for a in res['acc']], label=nom)

    for ax, title, ylabel in zip(axes,
                                  ["Perte (train)", "Precision (validation)"],
                                  ["Loss", "Accuracy (%)"]):
        ax.set_title(title)
        ax.set_xlabel("Epoque")
        ax.set_ylabel(ylabel)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("resultats_regularisation.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("\n Graphe sauvegarde : resultats_regularisation.png")

    return resultats
resultats_reg = experience_regularisation()

""" Experience D - Dropout"""

def experience_dropout():
    print("\n" + "="*60)
    print("EXPERIENCE D : Impact du Dropout")
    print("="*60)
    dropout_rates = [0.0, 0.2, 0.4, 0.6]
    resultats = {}
    for dr in dropout_rates:
        print(f"\n  -> dropout = {dr}")
        model = ReseauFC(hidden_sizes=[512, 256, 128], dropout_rate=dr)
        opt = optim.Adam(model.parameters(), lr=1e-3)
        tl, vl, va = entrainer(model, opt, nb_epochs=8, verbose=False)
        resultats[dr] = {'train': tl, 'val': vl, 'acc': va}
        print(f"Meilleure acc val = {max(va)*100:.2f}%")
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Impact du Taux de Dropout", fontsize=14)
    for dr, res in resultats.items():
        axes[0].plot(res['train'], label=f"dropout={dr}")
        axes[1].plot(res['val'], label=f"dropout={dr}")
    axes[0].set_title("Perte - Entraînement")
    axes[1].set_title("Perte - Validation")
    for ax in axes:
        ax.set_xlabel("Epoque")
        ax.set_ylabel("Cross-Entropy Loss")
        ax.legend()
        ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("resultats_dropout.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("\n Graphe sauvegarde : resultats_dropout.png")
    return resultats
resultats_dropout = experience_dropout()

"""Experience E - Batch Size"""

def experience_batch_size():
    print("\n" + "="*60)
    print("EXPERIENCE E : Impact du Batch Size")
    print("="*60)

    batch_sizes = [16, 64, 256, 1024]
    resultats = {}

    for bs in batch_sizes:
        print(f"\n  -> batch_size = {bs}")
        loader = DataLoader(train_dataset, batch_size=bs, shuffle=True)
        model = ReseauFC(hidden_sizes=[256, 128], dropout_rate=0.3)
        opt = optim.Adam(model.parameters(), lr=1e-3)
        old_loader = train_loader
        globals()['train_loader'] = loader

        tl, vl, va = entrainer(model, opt, nb_epochs=5, verbose=False)
        resultats[bs] = {'acc': va, 'loss': tl}

        globals()['train_loader'] = old_loader

        print(f"Meilleure acc val = {max(va)*100:.2f}%")

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Impact du Batch Size (Adam, lr=1e-3)", fontsize=14)

    for bs, res in resultats.items():
        axes[0].plot(res['loss'], label=f"bs={bs}")
        axes[1].plot([a*100 for a in res['acc']], label=f"bs={bs}")

    axes[0].set_title("Perte - Entrainement")
    axes[0].set_ylabel("Loss")
    axes[1].set_title("Precision - Validation")
    axes[1].set_ylabel("Accuracy (%)")

    for ax in axes:
        ax.set_xlabel("Epoque")
        ax.legend()
        ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("resultats_batch_size.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("\n Graphe sauvegarde : resultats_batch_size.png")

    return resultats
resultats_batch = experience_batch_size()

"""Experience F - Architecture"""

def experience_architecture():
    print("\n" + "="*60)
    print("EXPERIENCE F : Profondeur vs Largeur du reseau")
    print("="*60)
    architectures = {
        "Petit [64]": [64],
        "Moyen [256,128]": [256, 128],
        "Profond [256,128,64]": [256, 128, 64],
        "Large [512,512]": [512, 512],
    }
    resultats = {}
    for nom, hidden in architectures.items():
        nb_params = sum(p.numel() for p in ReseauFC(hidden).parameters())
        print(f"\n  -> {nom} - {nb_params:,} parametres")

        model = ReseauFC(hidden_sizes=hidden, dropout_rate=0.3)
        opt = optim.Adam(model.parameters(), lr=1e-3)
        tl, vl, va = entrainer(model, opt, nb_epochs=7, verbose=False)

        resultats[nom] = {'acc': va, 'params': nb_params}
        print(f"Meilleure acc val = {max(va)*100:.2f}%")

    fig, ax = plt.subplots(figsize=(10, 5))
    fig.suptitle("Impact de l'Architecture ", fontsize=14)

    for nom, res in resultats.items():
        label = f"{nom} ({res['params']:,} params)"
        ax.plot([a*100 for a in res['acc']], marker='o', label=label)
    ax.set_xlabel("Epoque")
    ax.set_ylabel("Accuracy (%) - validation")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("resultats_architecture.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("\n Graphe sauvegarde : resultats_architecture.png")
    return resultats
resultats_arch = experience_architecture()

"""Téeechargement des Resultats"""

from google.colab import files
import os
print("Fichiers generes dans Colab :")
for f in os.listdir('.'):
    if f.endswith('.png'):
        size = os.path.getsize(f)
        print(f"  {f} ({size/1024:.1f} KB)")
